on:
  workflow_dispatch:
  workflow_run:
    workflows: [Create Release]
    types:
      - completed
jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: install yq 
        id: install-yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.5.0/yq_linux_amd64
          chmod +x yq_linux_amd64
          sudo mv yq_linux_amd64 /usr/local/bin/yq
          yq -V
      - name: hello
        run: |
          yq e ".image.tag=\"v1\"" -i "t.yml"
         
