on:
  workflow_dispatch:
  workflow_run:
    workflows: [Create Release]
    types:
      - completed
jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: install yq 
        id: install-yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.5.0/yq_linux_amd64
          chmod +x yq_linux_amd64
          sudo mv yq_linux_amd64 /usr/local/bin/yq
          yq -V
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: hello
        run: |
          yq e ".image.tag=\"v1\"" -i "t.yml"
      - name: Git commit qa-values file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Github actions-autocommit-update image tages in values file 
          push_options: --force
          file_pattern: 't.yml'

          
         
