on:
  workflow_dispatch:
  release:
    types: [released,prereleased,deleted]
jobs: 
  deploy:
    runs-on: ubuntu-latest

    env:
      TAG: 1.0.1

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: scale up qa cluster
        id: scale-up
        run: |
           echo "Scaling UP"
