name: Create Release
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          tag_name: v22.7.3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
