name: Create Release
on:
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest

    env:
      TAG: 3.0.1

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.TAG }}
          release_name: Release v${{ env.TAG }}
