name: Create Release
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs: 
  deploy:
    runs-on: ubuntu-latest

    env:
      TAG: v1.0.${{ github.run_number }}
      RELEASE: patch

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        
      - name: script
        run: |
          chmod +x script/release
          if [[ ${{ env.RELEASE }} == "patch" ]]; then
            x=$(/bin/bash ./script/release -p "patch version" | awk 'END{print}')
            echo "::set-output name=version::$x"
          fi
          echo "$x"
          
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
