name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs: 
  deploy:
    runs-on: ubuntu-latest

    env:
      TAG: v1.0.${{ github.run_number }}
      RELEASE: patch

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        
      - name: script
        id: script
        run: |
          x=$(/bin/bash ./script/release -p "patch version" | awk 'END{print}')
          echo $x
          echo "::set-output name=version::$x"
          
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.script.outputs.version }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
